name: Scan CVEs dispatch

on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *"

jobs:

  get-images:
    runs-on: ubuntu-latest
    permissions:
      packages: read
      contents: read
    outputs:
      images: ${{ steps.get-images.outputs.images }}
    steps:
      - id: get-images
        name: Get GHCR image tags for current repo
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_OWNER: ${{ github.repository_owner }}
          GH_REPO: ${{ github.event.repository.name }}
        run: |
          echo "Fetching GHCR image tags for ghcr.io/${GH_OWNER}/${GH_REPO}..."

          # fetch function
          fetch() {
            curl -s -H "Authorization: Bearer $GH_TOKEN" -H "Accept: application/vnd.github+json" "$1"
          }

          # Determine if owner is a user or org (orgs have a separate endpoint)
          owner_type=$(fetch https://api.github.com/users/$GH_OWNER | jq -r '.type')

          if [ "$owner_type" == "Organization" ]; then
            versions=$(fetch "https://api.github.com/orgs/$GH_OWNER/packages/container/$GH_REPO/versions")
          else
            versions=$(fetch "https://api.github.com/users/$GH_OWNER/packages/container/$GH_REPO/versions")
          fi

          # Pull out every tag, prefix with the registry path
          image_list=$(echo "${versions}" | jq -r '.[] | .metadata.container.tags[]?' | sed "s|^|ghcr.io/${GH_OWNER}/${GH_REPO}:|")

          # Convert image_list to JSON array
          json_array=$(echo "$image_list" | jq -R -s -c 'split("\n") | map(select(. != ""))')

          # Set the job output
          echo "images=$json_array" >> "$GITHUB_OUTPUT"

  run-scan:
    name: Run scan for released images
    needs: [get-images]
    uses: canonical/oci-factory/.github/workflows/Vulnerability-Scan.yaml@ROCKS-2216/modify-cve-scanning # TODO update to main
    strategy:
      matrix:
        images: ${{ fromJson(needs.get-images.outputs.images) }}
    with:
      oci-image-name: ${{ matrix.images }}
      create-issue: true
    secrets: inherit
